version: '3'

services:
    web:
        build: .
        image: wolfangtorres/base-apache2-flask
        ports:
            - "8080:80"
        volumes:
            - apache2-logs:/var/log/apache2

volumes:
    apache2-logs:
